### PR TITLE
Update to llm-samplers v0.0.7

### PR DESCRIPTION
**Pull request by KerfuffleV2**
I'm not sure how you feel about putting `llm-samplers` in the main workspace. It's convenient right now when I was trying to get it to compile but that can be changed.

This is a little awkward also because it depends on `llm`, luckily I already had a pull there so I was able to point your deps at that.

### CODE REVIEW

**Comment by KerfuffleV2** [comment]
This shouldn't be merged yet but is ready for review. You'll probably want to wait until after `llm` merges also (I'm assuming that won't be an issue).

I will change the deps to point to the actual version instead of the repo. Please let me know if you want me to also change the workspace dependencies back to how it was originally, or any other changes.

**Comment by ealmloff** [comment]
The workspace dependancies are good. I updated some dependancies to workspace dependancies at some point, but I haven't moved all shared dependancies to the workspace yet.

> By the way, did you know you have a rphi/src/lanuage_model.rs?

Yes, it is an odd name, but it just contains the wrapper needed for the `kalosm_language_model` trait

**Comment by KerfuffleV2** [comment]
> it is an odd name

I meant that it's "lanuage" instead of "lan**g**uage". :)

**Comment by ealmloff** [comment]
Oh, oops no I must have mistyped that 😆

**Review by ealmloff — APPROVED** [review]

**Comment by KerfuffleV2** [comment]
@ealmloff `llm-samplers` `0.0.7` has been released. I tried to resolve the conflicts from #76. I didn't update the `llm` dependencies because you basically cannot merge this until they accept it otherwise. Right now, the pull there is exactly identical to their `main` branch except for the `llm-samplers` changes.

I'm not sure if you use `llm-samplers` in places that don't depend on `llm`, but if not (in other words, you're always going to be depending on `llm`) you might want to just not depend on `llm-samplers` in Floneum and always just use it through the `llm` re-export. That would tie you to their updates even more closely, so maybe there's a downside also. Just an idea.

This now merges but I can't compile (it runs into plugin issues, doesn't look to be related to `llm-samplers`). I also had to manually edit the `Cargo.lock` to make it point to my update in the `llm` pull. Since I had to do weird stuff, you probably need to double check to make sure I didn't break anything with my flailing around.

**Comment by ealmloff** [comment]
Thank you!

**Pull request merged**
